// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using FrmHome.Entities;

namespace FrmHome
{
    public partial class ExaminationContext
    {

        [DbFunction("getQuestionMark", "dbo")]
        public static int? getQuestionMark(int? q_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("getStudentGrade", "dbo")]
        public static int? getStudentGrade(int? crs_id, int? std_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
