// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Course_Attendance
    {
        [Key]
        public int crs_id { get; set; }
        [Key]
        public int std_id { get; set; }
        [Key]
        public int ins_id { get; set; }
        public int? grade { get; set; }

        [ForeignKey(nameof(crs_id))]
        [InverseProperty(nameof(Course.Course_Attendances))]
        public virtual Course crs_ { get; set; }
        [ForeignKey(nameof(ins_id))]
        [InverseProperty(nameof(Instructor.Course_Attendances))]
        public virtual Instructor ins_ { get; set; }
        [ForeignKey(nameof(std_id))]
        [InverseProperty(nameof(Student.Course_Attendances))]
        public virtual Student std_ { get; set; }
    }
}