// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Exam_Answer
    {
        [Key]
        public int std_id { get; set; }
        [Key]
        public int ex_id { get; set; }
        [Key]
        public int q_id { get; set; }
        [StringLength(1)]
        public string std_answer { get; set; }
        public int? std_mark { get; set; }

        [ForeignKey(nameof(ex_id))]
        [InverseProperty(nameof(Exam.Exam_Answers))]
        public virtual Exam ex_ { get; set; }
        [ForeignKey(nameof(q_id))]
        [InverseProperty(nameof(Question.Exam_Answers))]
        public virtual Question q_ { get; set; }
        [ForeignKey(nameof(std_id))]
        [InverseProperty(nameof(Student.Exam_Answers))]
        public virtual Student std_ { get; set; }
    }
}