// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Exam_Question
    {
        [Key]
        public int ex_id { get; set; }
        [Key]
        public int q_id { get; set; }

        [ForeignKey(nameof(ex_id))]
        [InverseProperty(nameof(Exam.Exam_Questions))]
        public virtual Exam ex_ { get; set; }
        [ForeignKey(nameof(q_id))]
        [InverseProperty(nameof(Question.Exam_Questions))]
        public virtual Question q_ { get; set; }
    }
}