// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Exam
    {
        public Exam()
        {
            Exam_Answers = new HashSet<Exam_Answer>();
            Exam_Questions = new HashSet<Exam_Question>();
        }

        [Key]
        public int ex_id { get; set; }
        [Column(TypeName = "date")]
        public DateTime date { get; set; }
        public int crs_id { get; set; }

        [ForeignKey(nameof(crs_id))]
        [InverseProperty(nameof(Course.Exams))]
        public virtual Course crs_ { get; set; }
        [InverseProperty(nameof(Exam_Answer.ex_))]
        public virtual ICollection<Exam_Answer> Exam_Answers { get; set; }
        [InverseProperty(nameof(Exam_Question.ex_))]
        public virtual ICollection<Exam_Question> Exam_Questions { get; set; }
    }
}