// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class getAllInstructorsResult
    {
        public int usr_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public decimal? salary { get; set; }
        public string degree { get; set; }
        public int dept_id { get; set; }
        public string dept_name { get; set; }
    }
}
