// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class getAllDepartmentsResult
    {
        public int dept_id { get; set; }
        public string dept_name { get; set; }
        public int mgr_id { get; set; }
    }
}
