// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class getQuestionAndStudentAnswerResult
    {
        public int std_id { get; set; }
        public int ex_id { get; set; }
        public int q_id { get; set; }
        public string std_answer { get; set; }
        public int? std_mark { get; set; }
        public string crs_name { get; set; }
        public string top_name { get; set; }
    }
}
