// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Question
    {
        public Question()
        {
            Exam_Answers = new HashSet<Exam_Answer>();
            Exam_Questions = new HashSet<Exam_Question>();
        }

        [Key]
        public int q_id { get; set; }
        [Required]
        [StringLength(3)]
        public string q_type { get; set; }
        [Required]
        [StringLength(300)]
        public string q_text { get; set; }
        [Required]
        [StringLength(1)]
        public string corr_answer { get; set; }
        public int top_id { get; set; }

        [ForeignKey(nameof(top_id))]
        [InverseProperty(nameof(Topic.Questions))]
        public virtual Topic top_ { get; set; }
        [InverseProperty("q_")]
        public virtual MCQ MCQ { get; set; }
        [InverseProperty(nameof(Exam_Answer.q_))]
        public virtual ICollection<Exam_Answer> Exam_Answers { get; set; }
        [InverseProperty(nameof(Exam_Question.q_))]
        public virtual ICollection<Exam_Question> Exam_Questions { get; set; }
    }
}