// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class setCourseNameResult
    {
        [Column("Error Message")]
        public string ErrorMessage { get; set; }
    }
}
