// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Student
    {
        public Student()
        {
            Course_Attendances = new HashSet<Course_Attendance>();
            Exam_Answers = new HashSet<Exam_Answer>();
        }

        [Key]
        public int std_id { get; set; }
        public int dept_id { get; set; }

        [ForeignKey(nameof(dept_id))]
        [InverseProperty(nameof(Department.Students))]
        public virtual Department dept_ { get; set; }
        [ForeignKey(nameof(std_id))]
        [InverseProperty(nameof(User.Student))]
        public virtual User std_ { get; set; }
        [InverseProperty(nameof(Course_Attendance.std_))]
        public virtual ICollection<Course_Attendance> Course_Attendances { get; set; }
        [InverseProperty(nameof(Exam_Answer.std_))]
        public virtual ICollection<Exam_Answer> Exam_Answers { get; set; }
    }
}