// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class viewTopicMCQResult
    {
        public int QID { get; set; }
        public string Course { get; set; }
        public string Topic { get; set; }
        public string Question { get; set; }
        [Column("Choice a")]
        public string Choicea { get; set; }
        [Column("Choice b")]
        public string Choiceb { get; set; }
        [Column("Choice c")]
        public string Choicec { get; set; }
        [Column("Choice d")]
        public string Choiced { get; set; }
        [Column("Correct Answer")]
        public string CorrectAnswer { get; set; }
    }
}
