// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class viewTopicTFQResult
    {
        public int QID { get; set; }
        public string Course { get; set; }
        public string Topic { get; set; }
        public string Question { get; set; }
        [Column("Correct Answer")]
        public string CorrectAnswer { get; set; }
    }
}
