// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Course
    {
        public Course()
        {
            Course_Attendances = new HashSet<Course_Attendance>();
            Exams = new HashSet<Exam>();
            Ins_Courses = new HashSet<Ins_Course>();
            Topics = new HashSet<Topic>();
        }

        [Key]
        public int crs_id { get; set; }
        [Required]
        [StringLength(100)]
        public string crs_name { get; set; }

        [InverseProperty(nameof(Course_Attendance.crs_))]
        public virtual ICollection<Course_Attendance> Course_Attendances { get; set; }
        [InverseProperty(nameof(Exam.crs_))]
        public virtual ICollection<Exam> Exams { get; set; }
        [InverseProperty(nameof(Ins_Course.crs_))]
        public virtual ICollection<Ins_Course> Ins_Courses { get; set; }
        [InverseProperty(nameof(Topic.crs_))]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}