// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Department
    {
        public Department()
        {
            Instructors = new HashSet<Instructor>();
            Students = new HashSet<Student>();
        }

        [Key]
        public int dept_id { get; set; }
        [Required]
        [StringLength(100)]
        public string dept_name { get; set; }
        public int mgr_id { get; set; }

        [ForeignKey(nameof(mgr_id))]
        [InverseProperty(nameof(Instructor.Departments))]
        public virtual Instructor mgr_ { get; set; }
        [InverseProperty(nameof(Instructor.dept_))]
        public virtual ICollection<Instructor> Instructors { get; set; }
        [InverseProperty(nameof(Student.dept_))]
        public virtual ICollection<Student> Students { get; set; }
    }
}