// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class getAllCoursesResult
    {
        public int crs_id { get; set; }
        public string crs_name { get; set; }
    }
}
