// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class getAllExamsResult
    {
        public int ex_id { get; set; }
        public DateTime date { get; set; }
        public int crs_id { get; set; }
    }
}
