// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class GetUserResult
    {
        public int usr_id { get; set; }
        public string user_type { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string hashed_password { get; set; }
    }
}
