// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Ins_Course
    {
        [Key]
        public int crs_id { get; set; }
        [Key]
        public int ins_id { get; set; }
        public int? evaluation { get; set; }

        [ForeignKey(nameof(crs_id))]
        [InverseProperty(nameof(Course.Ins_Courses))]
        public virtual Course crs_ { get; set; }
        [ForeignKey(nameof(ins_id))]
        [InverseProperty(nameof(Instructor.Ins_Courses))]
        public virtual Instructor ins_ { get; set; }
    }
}