// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Instructor
    {
        public Instructor()
        {
            Course_Attendances = new HashSet<Course_Attendance>();
            Departments = new HashSet<Department>();
            Ins_Courses = new HashSet<Ins_Course>();
        }

        [Key]
        public int ins_id { get; set; }
        [Column(TypeName = "money")]
        public decimal? salary { get; set; }
        [StringLength(50)]
        public string degree { get; set; }
        public int dept_id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? hire_date { get; set; }

        [ForeignKey(nameof(dept_id))]
        [InverseProperty(nameof(Department.Instructors))]
        public virtual Department dept_ { get; set; }
        [ForeignKey(nameof(ins_id))]
        [InverseProperty(nameof(User.Instructor))]
        public virtual User ins_ { get; set; }
        [InverseProperty(nameof(Course_Attendance.ins_))]
        public virtual ICollection<Course_Attendance> Course_Attendances { get; set; }
        [InverseProperty(nameof(Department.mgr_))]
        public virtual ICollection<Department> Departments { get; set; }
        [InverseProperty(nameof(Ins_Course.ins_))]
        public virtual ICollection<Ins_Course> Ins_Courses { get; set; }
    }
}