// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class MCQ
    {
        [Key]
        public int q_id { get; set; }
        [Required]
        [StringLength(300)]
        public string ch_a { get; set; }
        [Required]
        [StringLength(300)]
        public string ch_b { get; set; }
        [Required]
        [StringLength(300)]
        public string ch_c { get; set; }
        [Required]
        [StringLength(300)]
        public string ch_d { get; set; }

        [ForeignKey(nameof(q_id))]
        [InverseProperty(nameof(Question.MCQ))]
        public virtual Question q_ { get; set; }
    }
}