// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class Topic
    {
        public Topic()
        {
            Questions = new HashSet<Question>();
        }

        [Key]
        public int top_id { get; set; }
        [Required]
        [StringLength(100)]
        public string top_name { get; set; }
        public int crs_id { get; set; }

        [ForeignKey(nameof(crs_id))]
        [InverseProperty(nameof(Course.Topics))]
        public virtual Course crs_ { get; set; }
        [InverseProperty(nameof(Question.top_))]
        public virtual ICollection<Question> Questions { get; set; }
    }
}