// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FrmHome.Entities
{
    public partial class User
    {
        [Key]
        public int usr_id { get; set; }
        [Required]
        [StringLength(1)]
        public string user_type { get; set; }
        [Required]
        [StringLength(50)]
        public string f_name { get; set; }
        [Required]
        [StringLength(50)]
        public string l_name { get; set; }
        [StringLength(150)]
        public string address { get; set; }
        [Required]
        [StringLength(90)]
        public string email { get; set; }
        [Required]
        [StringLength(255)]
        public string hashed_password { get; set; }

        [InverseProperty("ins_")]
        public virtual Instructor Instructor { get; set; }
        [InverseProperty("std_")]
        public virtual Student Student { get; set; }
    }
}